version: '3.4'
services:
  client:
    build:
      target: client
    environment:
      - POW_CLIENT_VERSION=${POW_CLIENT_VERSION:-1}
      - POW_CLIENT_TARGET=${POW_CLIENT_TARGET:-20}
      - POW_CLIENT_CONCURRENCY=${POW_CLIENT_CONCURRENCY:-10}
      - POW_CLIENT_SERVER_ADDR=${POW_CLIENT_SERVER_ADDR:-server:9000}
      - POW_CLIENT_LOG_LEVEL=${POW_CLIENT_LOG_LEVEL:-info}
      - POW_CLIENT_REQUEST_TIMEOUT=${POW_CLIENT_REQUEST_TIMEOUT:-1s}
