version: '3.4'
services:
  server:
    build:
      target: server
    environment:
      - POW_SERVER_VERSION=${POW_SERVER_VERSION:-0}
      - POW_SERVER_TARGET=${POW_SERVER_TARGET:-20}
      - POW_SERVER_CONCURRENCY=${POW_SERVER_CONCURRENCY:-1}
      - POW_SERVER_REDIS_URL=${POW_SERVER_REDIS_URL:-redis://redis:6379/}
      - POW_SERVER_SERVER_ADDR=${POW_SERVER_SERVER_ADDR:-}
      - POW_SERVER_SERVER_PORT=${POW_SERVER_SERVER_PORT:-9000}
      - POW_SERVER_LOG_LEVEL=${POW_SERVER_LOG_LEVEL:-debug}
      - POW_SERVER_RESPONSE_TIMEOUT=${POW_SERVER_RESPONSE_TIMEOUT:-3s}
      - POW_SERVER_HASH_EXP=${POW_SERVER_HASH_EXP:-1h}
      - POW_SERVER_HEADER_TIME_INTERVAL=${POW_SERVER_HEADER_TIME_INTERVAL:-1h}

  redis:
    image: "redis:alpine"
