version: '3.4'
services:
  server:
    build:
      target: server
    environment:
      - POW_SERVER_CONCURRENCY=${POW_SERVER_CONCURRENCY:-1}
      - POW_SERVER_REDIS_URL=${POW_SERVER_REDIS_URL:-redis://redis:6379/}
      - POW_SERVER_SERVER_ADDR=${POW_SERVER_SERVER_ADDR:-:9000}
      - POW_SERVER_LOG_LEVEL=${POW_SERVER_LOG_LEVEL:-info}
      - POW_SERVER_RESPONSE_TIMEOUT=${POW_SERVER_RESPONSE_TIMEOUT:-3s}
      - POW_SERVER_CHALLENGE_SIZE=${POW_SERVER_CHALLENGE_SIZE:-16}
      - POW_SERVER_TARGET_BITS=${POW_SERVER_TARGET_BITS:-20}
      - POW_SERVER_CHALLENGE_TTL=${POW_SERVER_CHALLENGE_TTL:-10m}

  redis:
    image: "redis:alpine"
